AllCops:
  TargetRubyVersion: 2.0

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

# Incompatible with Psych in Ruby 2.0.0
Security/YAMLLoad:
  Enabled: false
